# conf/config.yaml
defaults:
  - model: transformer-owt
  - optimizer: adamw-owt
project: cs336-basics
run_name: ${now:%Y%m%d_%H%M%S}
seed: 42
max_steps: 40_000
vocab_path: data/owt_train_32000_vocab.json
merges_path: data/owt_train_32000_merges.pkl
batch_size: 32
checkpoint_steps: 10_000
checkpoint_path: checkpoints/owt
val_interval: 400